export enum Duration {
  ONE_YEAR = 'DURATION_365_DAYS',
  ONE_MONTH = 'DURATION_30_DAYS',
  ONE_WEEK = 'DURATION_7_DAYS',
  ONE_DAY = 'DURATION_1_DAY',
}

export enum GroupPeriod {
  GROUP_BY_PERIOD_1_HOUR = 'GROUP_BY_PERIOD_1_HOUR',
  GROUP_BY_PERIOD_1_DAY = 'GROUP_BY_PERIOD_1_DAY',
}
